Feat/backend/milestone 2 pharmacy related api implementations
MohomedRashad/assessment pull request #25
Opened 2023-02-28 06:01 UTC by MohomedRashad

2023-02-28 06:19 UTC, Raam124 commented on apps/users/models.py
> +    id = models.BigAutoField(primary_key=True)
why added an external pk to pharmacy?

2023-02-28 06:19 UTC, Raam124 commented on apps/users/serializers.py
> +        if not all([validated_data.get('name'), validated_data.get('address'), validated_data.get('phone'), validated_data.get('postal_code')]):
only name and postal code is required

2023-02-28 06:19 UTC, Raam124 commented on apps/users/serializers.py
> +    Pharmacy.objects.create(user = instance, name = validated_data['name'], address = validated_data['address'], phone = validated_data['phone'], postal_code = validated_data['postal_code'])
you're creating a pharmacy object for every users

2023-02-28 06:19 UTC, Raam124 commented on apps/users/serializers.py
> +        fields = ['id', 'first_name', 'last_name', 'email', 'password', 'confirm_password', 'role', 'name', 'address', 'phone', 'postal_code']
only name and postal code are required here too. rename `name` to `pharmacy_name`

2023-02-28 06:19 UTC, Raam124 commented on apps/users/serializers.py
> +    name = serializers.CharField(required=False)
These fields are pharmacy model fields why are you defining those inside user serializer

2023-02-28 06:21 UTC, Raam124 requested changes

2023-02-28 06:21 UTC, Raam124 commented on apps/users/serializers.py
> +            'name': {'required': False},
same fields issue here too

2023-02-28 06:44 UTC, MohomedRashad commented on apps/users/models.py
> +    id = models.BigAutoField(primary_key=True)
It is because of an error we get in the console. Thought of addressing it.

2023-02-28 09:06 UTC, MohomedRashad commented on apps/users/serializers.py
> +    name = serializers.CharField(required=False)
Well without defining them, I was not able to get the data to the serializer. Is there a better way to do this? Did tried alot of things, but this is the only way which worked for me.

2023-02-28 16:31 UTC, Raam124 requested changes

2023-02-28 16:31 UTC, Raam124 commented on apps/users/serializers.py
> +        fields = ['id', 'first_name', 'last_name', 'email', 'password', 'confirm_password', 'role', 'pharmacy_name', 'postal_code']
This will trigger an error since these fields do not belong to user model

2023-02-28 16:31 UTC, Raam124 commented on apps/users/serializers.py
> +        fields = ['id', 'first_name', 'last_name', 'email', 'password', 'confirm_password', 'role', 'pharmacy_name', 'postal_code']
This will trigger an error since these fields do not belong to user model

2023-02-28 16:31 UTC, Raam124 commented on apps/users/serializers.py
> +            instance = get_user_model().objects.create(first_name = validated_data['first_name'], last_name = validated_data['last_name'], username = validated_data['email'], role = validated_data['r
instead of repeating the same block of code here you can check the role again after the instance is saved and create the pharmacy

2023-03-01 06:55 UTC, Raam124 requested changes

2023-03-01 06:55 UTC, Raam124 commented on apps/users/serializers.py
> +            instance.delete() #deleting the already created user instance before raising an error
do not delete the instance this will trigger an error if the user has any pending relation objects. Also, it's not recommended to delete it. just check the validation fields before creating the user based on the role and again create the pharmacy by checking the role. we don't wanna include the validation inside the logic.

2023-03-01 10:26 UTC, Raam124 requested changes

2023-03-01 10:26 UTC, Raam124 commented on apps/users/serializers.py
> +    role = validated_data.get('role')
these variables are not needed just access it directly

2023-03-01 10:26 UTC, Raam124 commented on apps/users/serializers.py
> +    if role == 'PHARMACY' and not all([pharmacy_name, postal_code]):
you're checking if the role is equal to a string value called `PHARMACY` it's not the correct way to check. Check if the role is equal to the role choice of `PHARMACY` that you defined in the models.

2023-03-01 10:26 UTC, Raam124 commented on apps/users/serializers.py
> +    if role == 'PHARMACY':
same above issue check with the defined role instead of a string

2023-03-01 11:06 UTC, Raam124 approved these changes

2023-03-01 11:07 UTC, merged