feat: customized the prescription response based on the user role
MohomedRashad/assessment pull request #38
Opened 2023-03-23 05:10 UTC by MohomedRashad

2023-03-23 09:31 UTC, Raam124 requested changes

2023-03-23 09:31 UTC, Raam124 commented on apps/GPService/views.py
why this big import change is required ?

2023-03-23 09:36 UTC, MohomedRashad commented on apps/GPService/views.py
@Raam124  There were duplicated imports, so I ran the organize imports command from vs code. Should I revert it back or keep it?

2023-03-23 09:39 UTC, Raam124 commented on apps/GPService/views.py
if there are duplicate imports remove them manually. Do not use vscode commands those are not efficient it may break the existing code. right now it changed the entire import structure. just revert it and remove duplicates manually

2023-03-23 09:41 UTC, MohomedRashad commented on apps/GPService/views.py
@Raam124  Alrighty.

2023-03-27 05:01 UTC, Raam124 approved these changes

2023-03-27 05:01 UTC, merged