Feat/backend/milestone3 customizing the form assessment ap is response based on user role
MohomedRashad/assessment pull request #40
Opened 2023-03-27 11:37 UTC by MohomedRashad

2023-03-28 04:01 UTC, Raam124 requested changes

2023-03-28 04:01 UTC, Raam124 commented on apps/GPService/views.py
why are you using a Viewset here instead of ModelviewSet?

2023-03-28 05:03 UTC, MohomedRashad commented on apps/GPService/views.py
@Raam124  I used the viewset here as we are explicitly defining the methods. Should I change it?

2023-03-28 05:17 UTC, Raam124 commented on apps/GPService/views.py
@MohomedRashad  why are you explicitly defining the methods?

2023-03-28 05:19 UTC, Raam124 requested changes

2023-03-28 05:19 UTC, Raam124 commented on apps/GPService/views.py
> +            queryset = queryset.filter(type=form_assessment_type)
this is worst-case scenario you're querying all objects above unwantedly and again filtering it's not recommended

2023-03-28 06:28 UTC, MohomedRashad commented on apps/GPService/views.py
@Raam124  Well this is what you told me to do. Since we require custom endpoints for the form assessments and feedbacks, this was the way I've implemented those. All most all of the methods are custom logics. So I thought the model viewset will not be required here.

2023-03-29 04:07 UTC, Raam124 requested changes

2023-03-29 04:07 UTC, Raam124 commented on apps/GPService/views.py
model view set can have custom methods too. List and retrieve don't have any complex custom logic as well.  Can easily go with a model view set.

2023-03-29 09:23 UTC, Raam124 requested changes

2023-03-29 09:23 UTC, Raam124 commented on apps/GPService/views.py
>      def list(self, request):
why are you overriding list method inside model view set ?

2023-03-30 04:53 UTC, Raam124 requested changes

2023-03-30 04:53 UTC, Raam124 commented on apps/GPService/views.py
> +            queryset = queryset.filter(type=form_assessment_type)
instead of hitting the database second time here you can query all at once.

2023-03-30 15:00 UTC, Raam124 requested changes

2023-03-30 15:00 UTC, Raam124 commented on apps/GPService/views.py
> +    def get_queryset(self):
what's this indentation change?

2023-03-30 15:00 UTC, Raam124 commented on apps/GPService/views.py
> +    def get_queryset(self):
there are multiple if/else here this part need optimization

2023-03-31 10:13 UTC, MohomedRashad commented on apps/GPService/views.py
> +    def get_queryset(self):
@Raam124  I saw this out of the class. Maybe I've missed it.

2023-04-03 04:20 UTC, Raam124 requested changes

2023-04-03 04:20 UTC, Raam124 commented on apps/GPService/views.py
> +    def get_queryset(self):
this is not an efficient way checkout django-filters library

2023-04-04 04:28 UTC, Raam124 requested changes

2023-04-04 04:28 UTC, Raam124 commented on project/settings.py
> +        'PORT': os.environ.get("DATABASE_PORT", '2222'),
why did you change the database port?

2023-04-04 04:30 UTC, MohomedRashad commented
@Raam124  Oh sorry about that. Will revert it back.

2023-04-04 17:38 UTC, Raam124 approved these changes

2023-04-04 17:38 UTC, merged