feat: implemented the availability sub resource
MohomedRashad/assessment pull request #42
Opened 2023-04-11 08:27 UTC by MohomedRashad

2023-04-12 04:06 UTC, Raam124 requested changes

2023-04-12 04:06 UTC, Raam124 commented on apps/GPService/views.py
> +    @action(methods=['get'], detail=False, url_path='(?P<doctor_id>[a-zA-Z0-9]+)/availabilities')
why did you use this regular expression in the URL path it allows basically every character possible it's not recommended

2023-04-12 09:19 UTC, Raam124 requested changes

2023-04-12 12:44 UTC, Raam124 requested changes

2023-04-12 12:44 UTC, Raam124 commented on apps/GPService/views.py
> +    @action(methods=['get'], detail=False, url_path='(?P<doctor_id>[a-f\d]{8}-[a-f\d]{4}-[a-f\d]{4}-[a-f\d]{4}-[a-f\d]{12})/availabilities')
@MohomedRashad  what's the point of using this kind of expression here ? why can't you use a simple one that used everywhere

2023-04-12 13:15 UTC, MohomedRashad commented on apps/GPService/views.py
> +    @action(methods=['get'], detail=False, url_path='(?P<doctor_id>[a-f\d]{8}-[a-f\d]{4}-[a-f\d]{4}-[a-f\d]{4}-[a-f\d]{12})/availabilities')
@Raam124  You mean to use the regular expression in the urls.py file instead of the method?

2023-04-12 13:19 UTC, Raam124 commented on apps/GPService/views.py
> +    @action(methods=['get'], detail=False, url_path='(?P<doctor_id>[a-f\d]{8}-[a-f\d]{4}-[a-f\d]{4}-[a-f\d]{4}-[a-f\d]{12})/availabilities')
@MohomedRashad no what's the point of using this expression first explain me that?

2023-04-12 14:53 UTC, MohomedRashad commented on apps/GPService/views.py
> +    @action(methods=['get'], detail=False, url_path='(?P<doctor_id>[a-f\d]{8}-[a-f\d]{4}-[a-f\d]{4}-[a-f\d]{4}-[a-f\d]{12})/availabilities')
@Raam124  In order to get the UUID of the doctor as a url while validating it, I have used the regex.
This is asample url:
http://localhost:8000/api/availabilities/75cefa7b-82dc-4dcb-a7ed-8b89b85f61c6/availabilities
Is there another way to do instead of using the regex?

2023-04-21 03:57 UTC, Raam124 requested changes

2023-04-21 03:57 UTC, Raam124 commented on project/urls.py
> +    path('api/availabilities/<uuid:doctor_id>/availabilities/', AvailabilityViewSet.as_view({'get': 'get_all_availabilities_for_a_given_doctor'}), name='doctor-availabilities'),
we can't break our entire API format for a single API. this is not the way to achieve it. just go with the previous way but only change the regex

2023-04-24 04:35 UTC, Raam124 requested changes

2023-04-24 04:35 UTC, Raam124 commented on apps/GPService/views.py
> +    @action(methods=['get'], detail=False, url_path='(?P<doctor_id>[a-f\d]{8}(?:-[a-f\d]{4}){3}-[a-f\d]{12})/availabilities')
`(?P<doctor_id>[^/.]+)` try this regex and let me know if it works

2023-04-24 04:49 UTC, Raam124 approved these changes

2023-04-24 04:49 UTC, merged