refactor: refactored the code to use the new doctor instance in the a…
MohomedRashad/assessment pull request #44
Opened 2023-06-12 11:09 UTC by MohomedRashad

…vailability model

2023-06-12 11:12 UTC, Raam124 requested changes

2023-06-12 11:12 UTC, Raam124 commented on apps/users/models.py
> +    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
what is the purpose of adding a UUID here?

2023-06-12 11:15 UTC, Raam124 requested changes
Check the comments

2023-06-12 11:19 UTC, MohomedRashad commented on apps/users/models.py
> +    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
@Raam124  Since the default primary key is an integer, it doesn't allow to change from the user table to the doctor table in the availability model. Hope I'm clear.

2023-06-12 11:21 UTC, MohomedRashad commented on apps/users/models.py
> +    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
The following error is what I got:
django.db.utils.ProgrammingError: cannot cast type uuid to integer LINE 1: ..." ALTER COLUMN "doctor" TYPE integer USING "doctor"::integer

2023-06-12 11:23 UTC, Raam124 commented on apps/users/models.py
> +    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
This is not required here also it's better to keep doctor id as integer since we already have user id as a UUID. Check the error properly and find a solution

2023-06-12 11:30 UTC, MohomedRashad commented on apps/users/models.py
> +    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
@Raam124  I did go through alot of solutions, but couldn't find a way around. Will try again.

2023-06-14 04:19 UTC, Raam124 requested changes

2023-06-14 04:19 UTC, Raam124 commented on apps/users/models.py
> +    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
why this UUID PK is still there ?

2023-06-14 05:03 UTC, Raam124 requested changes

2023-06-14 05:03 UTC, Raam124 commented on apps/GPService/models.py
> +    doctor = models.ForeignKey(Doctor, on_delete=models.CASCADE, related_name='availabilities', default=None)
why a default is added here ?

2023-06-14 05:03 UTC, Raam124 commented on apps/users/migrations/0014_doctor.py
what is this migration why are you created the model again ?

2023-06-14 05:03 UTC, Raam124 commented on apps/users/migrations/0011_auto_20230612_1532.py
why did you added a field call test at first?

2023-06-15 03:51 UTC, Raam124 approved these changes

2023-06-15 03:51 UTC, merged